# Generated by Django 6.0.3 on 2026-03-31 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_administrador_estudiante_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'dia',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'horario',
            },
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_curso',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_administrador', models.ForeignKey(db_column='id_administrador', on_delete=django.db.models.deletion.CASCADE, to='api.administrador')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='api.tipocurso')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='CursoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='api.curso')),
                ('id_tecnico', models.ForeignKey(db_column='id_tecnico', on_delete=django.db.models.deletion.CASCADE, to='api.tecnico')),
            ],
            options={
                'db_table': 'curso_tecnico',
            },
        ),
        migrations.CreateModel(
            name='CursoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo_maximo', models.IntegerField()),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='api.curso')),
                ('id_dia', models.ForeignKey(db_column='id_dia', on_delete=django.db.models.deletion.CASCADE, to='api.dia')),
                ('id_horario', models.ForeignKey(db_column='id_horario', on_delete=django.db.models.deletion.CASCADE, to='api.horario')),
            ],
            options={
                'db_table': 'curso_horario',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('id_curso_horario', models.ForeignKey(db_column='id_curso_horario', on_delete=django.db.models.deletion.CASCADE, to='api.cursohorario')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
            options={
                'db_table': 'inscripcion',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('metodo', models.CharField(max_length=20)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('id_inscripcion', models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='api.inscripcion')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
    ]
