# Generated by Django 6.0.3 on 2026-03-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dia_horario_tipocurso_curso_cursotecnico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
