# Generated by Django 6.0.3 on 2026-03-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_administrador_estado_estudiante_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='estado',
        ),
    ]
