# Generated by Django 6.0.3 on 2026-04-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_administrador_estado_remove_estudiante_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cupo_maximo',
            field=models.IntegerField(default=20),
        ),
    ]
