# Generated by Django 6.0.3 on 2026-04-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_curso_cupo_maximo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='cupo_maximo',
        ),
    ]
