# Generated by Django 6.0.3 on 2026-04-17 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_curso_cupo_maximo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursohorario',
            name='cupo_maximo',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='id_curso_horario',
        ),
        migrations.AddField(
            model_name='curso',
            name='cupo_maximo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='id_curso',
            field=models.ForeignKey(db_column='id_curso', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.curso'),
        ),
    ]
