# Generated by Django 6.0.3 on 2026-04-21 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_cursohorario_cupo_maximo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categoria_herramienta',
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('uso', models.TextField()),
                ('info_importante', models.TextField()),
                ('imagen_previa', models.ImageField(blank=True, null=True, upload_to='herramientas/fotos/')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_administrador', models.ForeignKey(db_column='id_administrador', on_delete=django.db.models.deletion.PROTECT, to='api.administrador')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoriaherramienta')),
            ],
            options={
                'db_table': 'herramienta',
            },
        ),
        migrations.CreateModel(
            name='Modelo3D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='herramientas/modelos/')),
                ('nombre_identificador', models.CharField(help_text='Nombre para identificar esta parte o variante', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('escala', models.FloatField(default=1.0)),
                ('rotacion_default', models.CharField(default='0,0,0', max_length=50)),
                ('posicion_default', models.CharField(default='0,0,0', max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('id_herramienta', models.ForeignKey(db_column='id_herramienta', on_delete=django.db.models.deletion.CASCADE, related_name='modelos_3d', to='api.herramienta')),
            ],
            options={
                'db_table': 'modelo_3d',
            },
        ),
    ]
