# Generated by Django 6.0.3 on 2026-05-06 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_categoriaherramienta_herramienta_modelo3d'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_recurso',
            },
        ),
        migrations.AddField(
            model_name='herramienta',
            name='stock_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='stock_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('id_curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='api.curso')),
            ],
            options={
                'db_table': 'practica',
                'unique_together': {('id_curso', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='PrestamoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_prestada', models.IntegerField()),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('prestado', 'Prestado'), ('parcial', 'Parcial'), ('devuelto', 'Devuelto')], default='prestado', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_herramienta', models.ForeignKey(db_column='id_herramienta', on_delete=django.db.models.deletion.CASCADE, to='api.herramienta')),
                ('id_inscripcion', models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='api.inscripcion')),
                ('id_practica', models.ForeignKey(db_column='id_practica', on_delete=django.db.models.deletion.CASCADE, to='api.practica')),
                ('id_tecnico', models.ForeignKey(db_column='id_tecnico', on_delete=django.db.models.deletion.CASCADE, to='api.tecnico')),
            ],
            options={
                'db_table': 'prestamo_herramienta',
                'unique_together': {('id_inscripcion', 'id_practica', 'id_herramienta')},
            },
        ),
        migrations.CreateModel(
            name='DevolucionHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.IntegerField()),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_tecnico_receptor', models.ForeignKey(db_column='id_tecnico_receptor', on_delete=django.db.models.deletion.CASCADE, to='api.tecnico')),
                ('id_prestamo', models.ForeignKey(db_column='id_prestamo', on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='api.prestamoherramienta')),
            ],
            options={
                'db_table': 'devolucion_herramienta',
            },
        ),
        migrations.CreateModel(
            name='RecursoPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('archivo_local', models.FileField(blank=True, null=True, upload_to='practicas/recursos/')),
                ('url_externa', models.URLField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('id_practica', models.ForeignKey(db_column='id_practica', on_delete=django.db.models.deletion.CASCADE, to='api.practica')),
                ('id_tipo_recurso', models.ForeignKey(db_column='id_tipo_recurso', on_delete=django.db.models.deletion.CASCADE, to='api.tiporecurso')),
            ],
            options={
                'db_table': 'recurso_practica',
            },
        ),
        migrations.CreateModel(
            name='PracticaHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.IntegerField()),
                ('id_herramienta', models.ForeignKey(db_column='id_herramienta', on_delete=django.db.models.deletion.CASCADE, to='api.herramienta')),
                ('id_practica', models.ForeignKey(db_column='id_practica', on_delete=django.db.models.deletion.CASCADE, to='api.practica')),
            ],
            options={
                'db_table': 'practica_herramienta',
                'unique_together': {('id_practica', 'id_herramienta')},
            },
        ),
    ]
