# Generated by Django 6.0.3 on 2026-05-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tiporecurso_herramienta_stock_disponible_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practica',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='recursopractica',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='practica',
            name='orden',
        ),
    ]
