# Generated by Django 6.0.3 on 2026-05-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_practica_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_practica',
            },
        ),
        migrations.AddField(
            model_name='practica',
            name='id_tipo_practica',
            field=models.ForeignKey(db_column='id_tipo_practica', null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tipopractica'),
        ),
    ]
