# Generated by Django 6.0.5 on 2026-05-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tipopractica_practica_id_tipo_practica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucionherramienta',
            name='id_prestamo',
        ),
        migrations.AlterField(
            model_name='practicaherramienta',
            name='id_practica',
            field=models.ForeignKey(db_column='id_practica', on_delete=django.db.models.deletion.CASCADE, related_name='herramientas', to='api.practica'),
        ),
        migrations.AlterField(
            model_name='recursopractica',
            name='id_practica',
            field=models.ForeignKey(db_column='id_practica', on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='api.practica'),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_inscripcion', models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='api.inscripcion')),
                ('id_practica', models.ForeignKey(db_column='id_practica', on_delete=django.db.models.deletion.CASCADE, to='api.practica')),
                ('id_tecnico', models.ForeignKey(db_column='id_tecnico', on_delete=django.db.models.deletion.CASCADE, to='api.tecnico')),
            ],
            options={
                'db_table': 'prestamo',
            },
        ),
        migrations.CreateModel(
            name='PrestamoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_prestada', models.IntegerField()),
                ('estado', models.CharField(choices=[('prestado', 'Prestado'), ('parcial', 'Parcial'), ('devuelto', 'Devuelto')], default='prestado', max_length=20)),
                ('id_herramienta', models.ForeignKey(db_column='id_herramienta', on_delete=django.db.models.deletion.CASCADE, to='api.herramienta')),
                ('id_prestamo', models.ForeignKey(db_column='id_prestamo', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.prestamo')),
            ],
            options={
                'db_table': 'prestamo_detalle',
                'unique_together': {('id_prestamo', 'id_herramienta')},
            },
        ),
        migrations.AddField(
            model_name='devolucionherramienta',
            name='id_prestamo_detalle',
            field=models.ForeignKey(db_column='id_prestamo_detalle', default=2, on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='api.prestamodetalle'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PrestamoHerramienta',
        ),
    ]
