# Generated by Django 6.0.5 on 2026-05-20 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_devolucionherramienta_id_prestamo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregada', 'Entregada'), ('aprobada', 'Aprobada'), ('reprobada', 'Reprobada')], default='pendiente', max_length=20)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentario_tecnico', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('id_inscripcion', models.ForeignKey(db_column='id_inscripcion', on_delete=django.db.models.deletion.CASCADE, to='api.inscripcion')),
                ('id_practica', models.ForeignKey(db_column='id_practica', on_delete=django.db.models.deletion.CASCADE, to='api.practica')),
            ],
            options={
                'db_table': 'practica_estudiante',
                'unique_together': {('id_inscripcion', 'id_practica')},
            },
        ),
        migrations.CreateModel(
            name='EvidenciaPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='practicas/evidencias/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('id_practica_estudiante', models.ForeignKey(db_column='id_practica_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='api.practicaestudiante')),
            ],
            options={
                'db_table': 'evidencia_practica',
            },
        ),
    ]
