# Generated by Django 6.0.5 on 2026-05-20 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_practicaestudiante_evidenciapractica'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='id_usuario_creador',
            field=models.ForeignKey(db_column='id_usuario_creador', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
