# Generated by Django 6.0.5 on 2026-05-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_practica_id_usuario_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo3d',
            name='archivo_esquema',
            field=models.ImageField(blank=True, null=True, upload_to='herramientas/esquemas/'),
        ),
    ]
