# Generated by Django 6.0.5 on 2026-06-01 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_modelo3d_archivo_esquema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id_tipo',
            field=models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.PROTECT, to='api.tipocurso'),
        ),
        migrations.AlterField(
            model_name='tipocurso',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('hora_inicio', 'hora_fin')},
        ),
    ]
