# Generated by Django 6.0.3 on 2026-06-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_curso_id_tipo_alter_tipocurso_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AficheComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase_ia', models.CharField(help_text='Ej: CAPACITOR, FPC, BOBINA', max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('imagen_referencia', models.ImageField(blank=True, null=True, upload_to='ia/afiches/referencias/')),
                ('imagen_simbolo', models.ImageField(blank=True, null=True, upload_to='ia/afiches/simbolos/')),
                ('descripcion_general', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('herramientas', models.ManyToManyField(blank=True, related_name='afiches_componentes', to='api.herramienta')),
            ],
            options={
                'db_table': 'afiche_componente',
            },
        ),
        migrations.CreateModel(
            name='AficheCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('id_afiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='api.afichecomponente')),
            ],
            options={
                'db_table': 'afiche_caracteristica',
            },
        ),
        migrations.CreateModel(
            name='AficheFuncion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('id_afiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='api.afichecomponente')),
            ],
            options={
                'db_table': 'afiche_funcion',
            },
        ),
        migrations.CreateModel(
            name='AficheMedicionPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('id_afiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_medicion', to='api.afichecomponente')),
            ],
            options={
                'db_table': 'afiche_medicion_paso',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='AficheMedicionRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ia/mediciones/recursos/')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], default='imagen', max_length=10)),
                ('id_paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='api.afichemedicionpaso')),
            ],
            options={
                'db_table': 'afiche_medicion_recurso',
            },
        ),
        migrations.CreateModel(
            name='AficheProcedimientoPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('id_afiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_procedimiento', to='api.afichecomponente')),
            ],
            options={
                'db_table': 'afiche_procedimiento_paso',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='AficheProcedimientoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ia/procedimientos/recursos/')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], default='imagen', max_length=10)),
                ('id_paso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='api.aficheprocedimientopaso')),
            ],
            options={
                'db_table': 'afiche_procedimiento_recurso',
            },
        ),
    ]
